services:
    - type: web
      name: job-agents-api
      env: node
      plan: free
      buildCommand: |
        echo "Starting build process..."
        echo "Current directory: $(pwd)"
        echo "Installing dependencies..."
        npm install
        echo "Building frontend..."
        npm run build
        echo "Building server..."
        npm run build:server
        echo "Build complete. Contents of dist folder:"
        ls -la dist/ || echo "dist folder not found"
        echo "Contents of current directory:"
        ls -la
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            fromDatabase:
                name: job-agents-db
                property: connectionString
      healthCheckPath: /api/health
      autoDeploy: true

databases:
    - name: job-agents-db
      databaseName: jobagents
      user: jobagents_user
      plan: free
