services:
    # Backend API Service
    - type: web
      name: job-agents-api
      env: node
      plan: free
      buildCommand: |
          cd server
          npm install
          npm run build
      startCommand: cd server && npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            fromDatabase:
                name: job-agents-db
                property: connectionString
          - key: FRONTEND_URL
            value: https://anvaia-site.onrender.com
      healthCheckPath: /api/health
      autoDeploy: true

    # Frontend Static Site
    - type: web
      name: job-agents-frontend
      env: static
      plan: free
      buildCommand: |
          npm install
          npm run build
          echo "Build completed. Contents of dist folder:"
          ls -la dist/
      staticPublishPath: ./dist
      envVars:
          - key: VITE_API_BASE_URL
            value: https://job-agents-api.onrender.com
      autoDeploy: true

databases:
    - name: job-agents-db
      databaseName: jobagents
      user: jobagents_user
      plan: free
